//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShooterGame
    {
        public int ID_game { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<int> score { get; set; }
    }
}
